---
title:  "st_crop() without tears"
subtitle: "Vanquishing the \"attribute variables are assumed to be spatially constant throughout all geometries\" warnings"
author: "Susannah Cowtan"
date: "08/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
library(rnaturalearth)
library(sf)
library(ggplot2)
suppressPackageStartupMessages(library(dplyr))
```

```{r fake_data}
species_df <- tibble(
  Longitude = c(3.8, 3.1, 3.4),
  Latitude = c(43.5, 43, 43.3)
)
```

```{r data_to_sf}
# Convert lat/long columns to a column of class geometry
species_sf <- st_as_sf(species_df, 
                       coords = c("Longitude", "Latitude"),
                       crs = st_crs(4326))
```

```{r coastline}
# Coastline geometry from rnaturalearth
coastlines <- ne_coastline(scale = 50, returnclass = "sf") %>%
  # Get rid of the annoying warning from st_crop about 
  # attributes assumed constant
  st_set_agr("constant")
```

```{r crop_map}
# Minmax dataset to crop map
minmax_sf <- tibble(
  Latitude = range(species_df$Latitude),
  Longitude = range(species_df$Longitude)
) %>%
  st_as_sf(coords = c("Longitude", "Latitude"),
           crs = st_crs(4326))

# Cropped map
coast_crop_sf <- minmax_sf %>%
    # Apply buffer to minmax points
    st_buffer(dist = 50000) %>%
    # Draw box around buffer
    st_bbox(crs = st_crs(species_sf)) %>%
    # Crop to box - look!  No warnings!
    st_crop(coastlines, .)
```

```{r plot}
ggplot() +
    geom_sf(data = coast_crop_sf) +
    geom_sf(data = species_sf, colour = "blue", size = 3) +
    coord_sf(crs = st_crs(4326))
```

